import './globals.css'
import { Inter } from 'next/font/google'
import NavigationBar from './home/components/NavigationBar'
import Banner from './home/components/Banner'
import Footer from './home/Footer'
import SessionProvider from './SessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Meraki',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className="flex flex-col min-h-screen overflow-y-scroll">
        <SessionProvider>
          <NavigationBar />
        </SessionProvider>
        <Banner />
          {children}
        <div className='mt-auto'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
